esphome:
  name: bathroom_environment_sensor
  platform: ESP32
  board: esp32doit-devkit-v1

# Enable logging
logger:
  level: DEBUG

sensor:
  - platform: dht
    pin: GPIO4
    temperature:
      id: "environment_bathroom_temperature"
      name: "Bathroom Temperature"
      device_class: "temperature"
      state_class: "measurement"
      accuracy_decimals: 1
      filters:
        - lambda: return x * (9.0/5.0) + 32.0;
        - median:
            window_size: 5
            send_every: 5
      unit_of_measurement: "°F"
    humidity:
      id: "environment_bathroom_humidity"
      name: "Bathroom Humidity"
      device_class: "humidity"
      state_class: "measurement"
      accuracy_decimals: 0

      filters:
        - median:
            window_size: 5
            send_every: 5
    update_interval: 10s


esp32_ble_beacon:
  type: iBeacon
  uuid: '9fa138b5-8759-4889-a4c6-f6f4bf684e68'

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address

mqtt:
  broker: 192.168.0.2
  port: 1883
  topic_prefix: "home/bedroom"
  discovery: false


api:
  port: 6053

ota:
  password: ""

wifi:
  ssid: "GT HOYA2019"
  password: "GT HOYAS2019"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bathroom Enviornmental Sensor"
    password: "password"

captive_portal:


web_server:
  port: 80